[package]
name = "klippit"
version = "1.1.1"
description = "Frame-accurate clip/GIF/screenshot export panel, triggered from mpv"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "devtools"] }
tauri-plugin-single-instance = "2"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "klippit"
path = "src/main.rs"
